### ISSUE TITLE
What is the license which applies to this repository?

### ISSUE THREAD

**Issue by ifraixedes** [louisstow/fann.js#2]
Hi, 

What is the license that you're releasing this work?

Thanks.

**Comment by louisstow** [comment]
I'll probably just do MIT. That sound ok?

**Comment by ifraixedes** [comment]
For me it's perfect, nonetheless I'm happy whatever the authors decide, the key thing is providing a clear license to allow to the people to know that they can and cannot do with the code.

Thanks.
